version: '2.1.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Whois/Whois.csproj --verbosity m
build_script:
  # output will be in ./Whois/Whois/bin/Release/{framework}
  - cmd: dotnet build ./Whois/Whois.csproj -c Release -f netstandard2.0
  - cmd: dotnet build ./Whois/Whois.csproj -c Release -f net452
  - cmd: dotnet pack ./Whois/Whois.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
- path: .\**\*.nupkg
  name: Package
  type: NuGetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Whois.Tests/Whois.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd Whois.Tests
  - cmd: dotnet test
on_finish :
